### ISSUE TITLE
When user is admin: false, sudoer: true, they don't receive admin emails

### ISSUE THREAD

**Issue by jcormier** [AlphaNodes/redmine_sudo#1]
Noticed that we weren't receiving account activation emails reliably.

Just tracked it down to this plugin.  Since the plugin converts everyone from admin to sudoers, except when in "admin mode".  Those users don't get the proper admin emails, except if they happen to be admin at the time.

A list of functions that send an email to all admins:

* mailer.rb: deliver_settings_updated
users = User.active.where(admin: true).to_a
* user.rb: deliver_security_notification
users = User.active.where(admin: true).to_a
* mailer.rb: deliver_account_activiation_request
users = User.active.where(:admin => true)

I'm assuming a fix would be to also grab users who are sudoers in these functions, but I'm not sure how to override these functions from the plugin...

something like: 

    User.where('admin: true OR sudoer: true')

**Comment by alexandermeindl** [comment]
Hi @jcormier,

good catch, you are right. `where(sudoer: true)` should be enough for usage with this plugin (without or admin - because there is no admin, who is not a sudoer). I have to think about it, if there is a solution for this problem. Ideas are welcome 😏

**Comment by jcormier** [comment]
I'm not familiar with how the plugin patches work.  Is it possible to override these functions? Though idk how fragile that would be upon redmine updates.

**Comment by alexandermeindl** [comment]
Override these functions can be overwritten, sure. But maybe I/we find another solution without overwriting complete functions.

**Comment by jcormier** [comment]
Hmm can we somehow monkey patch it so before the function is called we set it  up so the admin query works like normal, then restore it after the call is done?  This seems more complicated than replacing the function...  I don't know ruby/rails all that well, so hard to know how plugins usually handle this scenario.

**Comment by alexandermeindl** [comment]
Hi @jcormier,

can you try it with my latest commit, this should solve the problem. It is not a clean solution, because 2 methods are overwritten completely. But for the moment, I do not see a better solution.

**Comment by jcormier** [comment]
I had to patch tag v1.0.2 since I'm still running redmine 4.2, however it does appear to be working.  

You missed the "user.rb: deliver_security_notification" notification. But with your current patch settings updates and account activations are sending emails to all admins now.

Note: I checked the redmine code in their repo and the code we are overriding hasn't changed since 2018 when they did the big mail async change.  It does mean this change probably isn't compatible for redmine versions earlier than 3.4.x (I think..) but otherwise the code is at least fairly stable and doesn't get updated often.

**Comment by alexandermeindl** [comment]
> You missed the "user.rb: deliver_security_notification" notification. But with your current patch settings updates and account activations are sending emails to all admins now.

I did not miss it, there is no change required for it. Just test it. Let me know if there are problems left.

**Comment by jcormier** [comment]
> I did not miss it, there is no change required for it. Just test it. Let me know if there are problems left.

Huh okay. I set someone as admin and then removed them.  Neither action sent any emails so I guess I don't know how that feature works.

**Comment by alexandermeindl** [comment]
Hi @jcormier,
you are right, my fault, sorry. I'll take a look at this.

**Comment by alexandermeindl** [comment]
Hi @jcormier,
Can you try it again, if security notifications now works with admin changes?

**Comment by jcormier** [comment]
That works. Thanks.  Tested on redmine 4.2.2
